### ISSUE TITLE
returnVersion should not swallow errors

### ISSUE THREAD

**Issue by sohkai** [aragon/apm.js#12]
Users should swallow them, rather than doing so by default.

For example, [`getAllVersions()`](https://github.com/aragon/apm.js/blob/fc6d29e0c63e9fe531d98e127bbb305fd38338f9/src/index.js#L181) should be adding the `.catch(() => {})` when it launches promises.

**Comment by bingen** [comment]
Hey @sohkai , I think this is solved with this commit: c7ccb56dca1bd0130aa67f22265cb4e6d06caca1
Do you think we can close this issue?
Cc: @izqui

**Comment by sohkai** [comment]
It's still swallowing the error, but at least we're providing a default. Let's close it until we realize we need better error handling.
